config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  get    '/logout',           to: 'sessions#destroy'

  get    '/calendar',         to: 'calendars#index'

  get    '/activity_imports', to: redirect('activity_imports/new')
  get    '/purchase_imports', to: redirect('purchase_imports/new')
  resources :activity_imports, only: [:new, :create]
  resources :purchase_imports, only: [:new, :create]

  resources :products
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
	    <li><%= link_to "Log Out", logout_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "GustiLogistics", root_path, id: "logo" %>
	  <nav>
	    <ul class="nav navbar-nav navbar-right" id="header-tags">
        <% if logged_in? %>
          <li><%= link_to "Calendar", '/calendar' %></a></li>
          <li><%= link_to "Products", products_path %></li>
          <li class="drowdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Uploads <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/activity_imports/new">Unit Activity Report</a></li>
              <li><a href="/purchase_imports/new">Items Sold to Customer</a></li>
            </ul>
          </li>
        </ul>
        <% else %>
	        <li><%= link_to "Home", root_path %></li>
        <% end %>
      </ul>
	  </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= render 'layouts/shim' %>
  </head>

  <body>
	  <%= render 'layouts/header' %>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>
      <%= yield %>
	    <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>